### ISSUE TITLE
Convert Siderbar.test to RTL completely :P

### ISSUE THREAD

**Issue by tigerabrodi** [kcdraidgroup/hospitalrun-frontend#12]
This is a heavy one :100:

**Comment by tigerabrodi** [comment]
I am unassigned myself for now, here is the PR https://github.com/kcdraidgroup/hospitalrun-frontend/pull/34, a good first issue as well for newcomers.

Would be happy if others could make progress on it :tada:

**Comment by emma-r-slight** [comment]
Hey, keen to continue from where you left off!!

**Comment by tigerabrodi** [comment]
@emma-r-slight You got it! :tada: :partying_face:
