### ISSUE TITLE
Investigate console.error for: Warning: React has detected a change in the order of Hooks called by NewImagingRequest...

### ISSUE THREAD

**Issue by mpeyper** [kcdraidgroup/hospitalrun-frontend#195]
So [this test](https://github.com/kcdraidgroup/hospitalrun-frontend/blob/master/src/__tests__/imagings/requests/NewImagingRequest.test.tsx#L135) is not doing what the description says.

It's failing to save the imaging request, instead there is a validation error that the patient is required, which the test is conveniently [asserting is logged](https://github.com/kcdraidgroup/hospitalrun-frontend/blob/master/src/__tests__/imagings/requests/NewImagingRequest.test.tsx#L136) and also [asserts that the final location is actually where it started and not where the description says it should be](https://github.com/kcdraidgroup/hospitalrun-frontend/blob/master/src/__tests__/imagings/requests/NewImagingRequest.test.tsx#L156).

However, none of that is the reason why the warning is being produced.  That's happening because the test is not awaiting the save allowing to to pass its bogus assertion and begin the cleanup.  When the async does resolve, the [mocked useUpdateTitle hook](https://github.com/kcdraidgroup/hospitalrun-frontend/blob/master/src/__tests__/imagings/requests/NewImagingRequest.test.tsx#L28) has been restored back to it's former glory so when the component rerenders, there is an additional useContext call in the tree.

There are 2 actions here:

1. Update the test to do what it says it's going to do
2. Ensure the component is idle before the the tests ends and cleanup occurs

There is a good chance that doing 1 will cause 2 to happen as well.

Further details:

* The `imagings.imaging.patient` combobox is an `Typeahead` that searches asynchronously (I think)
  * This could be why it is considered missing when the `Create` button is clicked

Note: I am not assigning myself to this at this point in time, I was only investigating the issue as it seemed related to hooks.

**Comment by nobrayner** [comment]
Hmm... That explains why it was passing. I should have paid more attention instead of just hiding errors :roll_eyes: :man_facepalming:
